http:
  private:
    port: "8091"
  
autodiscovery: "20572004"

# Configuración del normalizador (se lee de CloudHub Properties con valores por defecto)
normalizador:
  tipo: "${normalizador.tipo:CATASTRO}"          # CloudHub Property - Default: CATASTRO
  fallback: "${normalizador.fallback:true}"      # CloudHub Property - Default: true
  timeout: "30000"                               # Timeout fijo en ms


anypoint:
  platform:
    client_id: "d0f8c76053564a4dbba306392a96fec0"
    client_secret: "58cB540Ae2504D668FbC77fB98286125"
    
mongo-db-sapi:  
  protocol: "HTTP"  
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/mongo/v1"
  path:
    geoAddress: "/address/geoAddress"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
configurationTimeout:
  mongo-db-sapi: "62000"
  smallworld-sapi: "61000"
  
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

smallworld-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-smallworld-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/smallworld/v1"
  path:
    coverage: "/coverage"
    geocodificar: "/geocodificar"
    georeference: "/georeference"
  username: "7b167b9c389a4c0099bbf7ea34df88fc"
  password: "8917F36fBC2c4105b72c7bC3a165740F"