http:
  private:
    port: "8091"

global:
  txrMaxPorHora: "100"

configurationTimeout:
  mdm-db: "60000"
  or-db: "60000"
  prtl_pro_bd: "60000"
  audits-mongo: "60000"
  mvne-db: "60000"
  selectionTimeout: "60"
  socketTimeout: "30000"
  minPoolSize: "5"
  maxIdleTime: "30000"
  reconnect:
    frequency: "5000"
    attempts: "3"

api_id: "mongo-sapi-services-prod"

mongoDb:
  host: "10.60.22.9"
  port: "27030"
  database: "OR"
  username: "USRPRTLOR"
  password: "2KS#ZQfd13"
  collectionName: OR_ORDEN
  collectionRtaViabilidad: "OR_RTA_VIABILIDAD"
  collectionRtaProvisioning: "OR_RTA_APROVISIONAMIENTO"
  collectionRTA: "OR_RESPUESTA"
  collectionCtaFact: "OR_CUENTAS_FACTURACION"
  collectionHomologacionFacturacion: "OR_HOMOLOGACION_FACTURACION"
  collectionConsecutivo: "OR_CONSECUTIVO"
  collectionOrden: "OR_ORDEN"
  collectionParametro: "OR_PARAMETRO"
  collectionIntegracionesTramites: "OR_PAR_INTEGRACIONES_TRAMITES"
  collectionLogMessages: "MVNE_SMSC_LOG"
  collectionEnrutadorMensajes: "MVNE_SMSC_EnrutadorDatos"

mongoDb-imei:
  host_list:   
    host1: "VM-AZMONGODB07.etb.cloud"
    host2: "VM-AZMONGODB08.etb.cloud"
  port: "37017"
  database: "MULESOFT"
  username: "mulemvne_mongo_prd"
  password: "dDHxN99u3JUW7xu"

mongoDb-mdm:
  host_list:
    host1: "VM-AZMONGOS03.etb.cloud"
    host2: "VM-AZMONGOS04.etb.cloud"
  port: "27030"
  database: "MDM"
  database-parametrization: "PRTL_PRO_BD"
  username: "Mule_mongo_prod"
  password: "Z*s985S8"
  collection-wspPlantilla: "ADM_WHATSAPP_PLANTILLAS"
  portabilidadProcesos: "MDM_PORTABILIDAD_SOLICITUDES"
  #portabilidadProcesos: "MDM_PORTABILIDAD_PROCESOS"
  otiniciativas:
    collection-interaction: "MDM_INTERACCION_CD"
    collection-parametersMs: "MULESOFT_PARAMETROS"
    collection-manualEquipo: "MDM_PI_MANUALEQUIPO"
    collection-acuerdos: "MDM_CD_FIRMAS_ACUERDOS"
    collection-acuerdos-logs: "MDM_CD_LOG_FIRMA_DOCS"
    collection-interaction-hcm: "MDM_HSM_INTERACCION"
    collection-logs: "MDM_HSM_INTERACCION_LOG"
    collection-pqrAgendaTmr: "PQR_AGENDA_TMR"
  tibco:
    collection: "MDM_INTEGRATION_MSG"
    collection-ctaFact: "MDM_CUENTA_FACTURACION"
    collection-factOnline: "MDM_FACTURA_ONLINE"
    collection-parameters: "PAR_PARAMETROS"
  mayoristas:
    collection-order: "MDM_CD_ORDEN"
    collection-order-completed: "MDM_CD_ORDEN_COMPLETADA"
    collection-consecutive: "MDM_CD_CONSECUTIVO"
    collection-parameter: "MDM_CD_PARAMETRO"
    collection-guionStatus: "MDM_CD_GUION_ESTADOS"
    collection-department: "PAR_DEPARTAMENTO"
    collection-city: "PAR_CIUDAD"
    collection-status-description: "MDM_CD_ESTADOS"
    collection-causal: "MDM_CD_CAUSALES_MAYORISTA"
    collection-services: "MDM_CD_SERVICIO"
    collection-client: "MDM_CLIENTE"
    collection-rneMoviles: "MDM_SERVICIO_ACTIVO"
    collection-loginPosteria: "MDM_PI_USUARIO_INSTALACION"
    collection-ofertaProducto: "CMP_OFERTA_PRODUCTO"
    collection-movimientoMat: "MDM_MOVIMIENTO_MAT_TRAN"
    collection-tramites: "COLL_TRAMITES"
    collection-offers: "PORTAL_UNIFICADO_OFFER"
    serie-orderNumber: "SecuenciaOrdenMayorista"
    serie-serviceAccount: "SecuenciaCuentaServicioMayorista"
    parameter-type: "ESTRUCTURA_ORDEN_VTA_MAY"
    format-consecutive : "0000"
    format-date: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    collection-referral: "MDM_REFERIDOS_EMEPLEADOS"
    collection-commercialCatalog: "CATALOGO_COMERCIAL_SVAS"
  ecommerce:
    collection-client: "MDM_CLIENTE"
    collection-users: "PORTAL_UNIFICADO_USUARIO"
    collection-multiuser: "PORTAL_UNIFICADO_MULTIUSUARIOS"
  pqr:
    collection: "PQR_PQR"
    collection-compensations: "PQR_COMUNICACIONES_COMPENSACIONES_FALLA_MASIVA"
    estado: "estado_pqr_homologado"
    sintoma_mietb: "CAMBIO METODO ENVIO DE FACTURA"
    falla-masiva: "PQR_FALLA_MASIVA_NUEVO"
  products:
    key: "products"

  billing:
    parametrization-collection: "BOT_PARAMETRIZATION"
    order-mobile-collection: "MDM_ORDEN"
    order-house-collection: "MDM_CD_ORDEN"
    order-service-collection: "MDM_ORDEN_SERVICIO"
    bill-amount-collection: "MDM_CASAS_COBRANZA"
    online-bill-collection: "MDM_FACTURA_ONLINE"
    activeService:
      collection: "MDM_SERVICIO_ACTIVO"
      fields: ","
    service:
      collection: "MDM_CD_SERVICIO"
      fields: ","
  mulesoft:
    tokens: "MULESOFT_TOKENS"
    clients: "MULESOFT_CLIENTES"
    systems: "MULESOFT_SISTEMAS"
  
mdm-integration:
  user: ""
  password: ""
  passwordTest: ""
  operation:
    provNplayOSM: "30"
    provLTEASAP: "20"

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs"
  path: "/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

retryConfiguration:
  maxRetry: "3"

scheduler:
  frequency: "24"

cacheKeys:
  typeParameters: "TP"

logging:
  deniedProcessName: "send_message"
  mayoristas:
    causal: "OFF"
    clientes: "OFF"
    ordenes:
      obtener: "OFF"
      actualizar: "OFF"
      insertar: "OFF"
    ordenesModelo: "OFF"
    status: "OFF"
    servicios: "OFF"

autodiscovery: "17861566"

referred:
  estado: "Activo"
  producto: "TELEFONIA MOVIL (LTE)"

mvne-db:
  host_list:
    host1: ""
    host2: ""
    host3: ""
  port: "27017"
  database: "MULESOFT"
  username: ""
  password: ""
  collection-token: "MULESOFT_JSC_PARAMETRIZATION"
  collection-systems: "MULESOFT_SISTEMAS"
  collection-promos: "MVNE_PROMOCIONES"
  collection-promos-pkg: "MVNE_PROMOCION_PAQUETE"
  collection-promo-user: "MVNE_PROMOCION_USUARIO"

mongoDb-autogestion:
  host_list:
    host1: "VM-AZMONGOS03.etb.cloud"
    host2: "VM-AZMONGOS04.etb.cloud"
  port: "27030"
  database: "PRTL_PRO_BD"
  username: "Mule_mongo_prod"
  password: "Z*s985S8"
  collection-catalogoComercial: "CATALOGO_COMERCIAL_SVA"

#Parametro de busqueda interaccion HSM en minutos
search-interaction: "15"

smpp:
  host: "10.55.138.141"
  port: "2775"
  systemId: "SMPPJSCETB"
  password: "sP1eTb$9" 
  sourceAddr: "88892"