http:
  private:
    port: "8091"
  
portal-fija-client:
  protocol: "HTTP"
  host: "10.112.71.148"
  port: "7004"
  basePath: "/PortalFijaWS"
  path: "/PortalFijaService"
  
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
autodiscovery: "18019688"

content-type: "application/text/xml action='http://PortalFijaWS.etb.com/lte/PortalFijaServicePortType/jerarquiaCuentaRequest'"

configurationTimeout:
  portal-fija: "60000"