http:
  private:
    port: "8091"
  host: "0.0.0.0"
  path: "/sisext/*"

autodiscovery: "17964741"

global-vars:
  refill: "Refill"

configurationTimeout:
  validateQuestionnaire: "120000"
  inOrderService: "60000"
  wsCoverageGIS: "70000"
  sisext: "180000"
  etbPymes: "120000"
  transunion: "60000"
  oracle-sapi: "60000"
  salesforceLD: "60000"
  vmr: "60000"
  prom-logic: "60000"
  audits-mongo: "60000"
  inetum: "60000"
  mediafon: "60000"
  sendMessage: "60000"
  atp: "60000"
  air: "60000"
  dgo: "60000"
  mongo-sapi: "60000"
  azsign: "60000"

sisext:
  protocol: "HTTP"
  host: "10.112.1.57"
  port: "8080"
  basepath: "/gss/web/services"
  path: "/WsM6ConsultarBloquearRecursosService?wsdl"
  
salesforceLD:
  protocol: "HTTP"
  host: "10.112.71.62"
  port: "7003"
  basepath: "/WSSalesForceLD"
  path: "/WSSalesForceLD"

wsCoverageGIS:
  protocol: "HTTP"
  host: "10.112.1.63"
  port: "8080"
  basepath: "/gss/web/services"
  path: "/WsGetFactibilidadServicios?wsdl"
  
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

inOrderService:
  protocol: "HTTPS"
  host: "etbcontingencia.nuaio.com"
  port: "30600"
  basePath: "/rest/api/submit-job"
  path: "/agendaETB"
  apiKey: "4909-7b34-5f41-4ce5-ae14-bda1-ea81-1c93"
  secretKey: "9911c6cb28804aa8b238730db65598f6"
  tls:
    path: "security/client_truststore_prod.ts"
    password: "mul3_ETBp"

temDataServices:
  protocol: "HTTP"
  host: "10.60.28.20"
  port: "8080"
  path: "/wsValida.asmx"
  credentials:
    user: "EtbProduccion"
    password: "2o3tbPr0dI7*"
  sistemaOrigen: "SIEBEL"
  headers:
    content-type: "text/xml; charset=utf-8"
    SOAPAction: "http://tempuri.org/IValidaService/ValidarCuestionario"
    
consultaCupoNegLISIM:
  properties:
    user: "EtbPymes2019"
    password: "*3Tb_Pyme$"
EtbPymes:
  protocol: "HTTP"
  host: "10.60.28.20"
  port: "6632"
  path: "/wsEtbPymes.asmx?wsdl"  
  autentication:
    user: "EtbPymes2019"
    password: "*3Tb_Pyme$"
  validaIdentidadNeglisim:
    soap-action: "http://tempuri.org/ValidarIdentificacion"
  consultaCupoNegLISIM:
    soap-action: "http://tempuri.org/CalculoCupo"  

etb-mdm-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-etb-mdm-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mdm"
  registerLog:
    path: "/v1/registerLog"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

WSResponseVerificaDocumentoCIFIN:
  protocol: "HTTPS"
  host: "miportafolio.transunion.co"
  port: "443"
  basepath: "/InformacionComercialConValidacionWS/services"
  path: "/InformacionComercial?wsdl"
  action: "http://infocomercial.cifin.asobancaria.com/InformacionComercialWS/consultaXmlRequest"
  auth:
    basic:
      user: "599679"
      pass: "Et8202"
    tls:
      type: "JKS"
      path: 'src\main\resources\security\ETB_INFORMACIONCOMERCIALCONVALIDACIONWS_PROD.jks'
      alias: "cifpro119057_0154_19062025"
      keypass: "2025Mul3Sf0t"
      pathJava: "security/ETB_INFORMACIONCOMERCIALCONVALIDACIONWS_PROD.jks"
    
oracle-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/oracle"
  path: "/v1/document/homologation/{idDocument}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
vmr-wsetb:
  protocol: "HTTP"
  host: "10.112.71.75"
  port: "80"
  basePath: "/WSETB"
  path: "/VMRWebServiceETB.asmx"
  
vmr:
  protocol: "HTTP"
  host: "appdinprd01.etb.com.co"
  port: "80"
  basePath: "/WSETB"
  path: "/VMRWebServiceETB.asmx"

prom-logic-ws:
  protocol: "HTTP"
  host: "40.118.188.146"
  port: "240"
  path: "/PromocionesLogicService.svc"
  contentType: "application/soap+xml"
  action: "http://www.etb.com.co/promociones-y-descuentos/IPromocionesLogicService/PROM_Promociones_Activo"
audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs/"
  path: "/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
wsFraude:
  protocol: "HTTP"
  host: "10.112.71.75"
  port: ""
  basePath: ""
  contentType: "text/xml;charset=UTF-8 action='Fraude_DWH/ConsultaFraude"
  path:
    fraudQuery: "FraudeETB/Fraude_DWH.asmx"    


# faltan propiedades productivas
air:
  protocol: "HTTP"
  host: "10.112.157.11"
  port: "10011"
  path: "/Air"
  content-type: "text/xml"
  user-agent: "IVR/5.0/1.0"
  auth: "dWNpcHRlc3Q6dWNpcHRlc3Q"
  
google:
  captcha: "https://www.google.com/recaptcha/api/siteverify"
  
wsCarvajal:
  protocol: "HTTPS"
  host: "tracking.carvajalcomunicacion.com"
  port: ""
  basePath: "wdelta/www_service/wservermain/L2RlbHRhL2Rlc2Fycm9sbG93Z"
  url: "https://tracking.carvajalcomunicacion.com/wdelta/www_service/wservermain/L2RlbHRhL2Rlc2Fycm9sbG93Z/doxETB1.php"
  headers:
    soapAction: "http://tracking.carvajalcomunicacion.com/wdelta/www_service/wservermain/L2RlbHRhL2Rlc2Fycm9sbG93Z/doxETB1.php/ReciboPagoEmp"
    contentType: "text/xml;charset=UTF-8"
    cookie: "WEBSVR=4"
  path:
    getInvoice: "doxETB1.php"

  
inetum:
  protocol: "HTTP"
  host: "10.50.0.4"
  port: "80"
  path: "/XCEWSCOLOMBIA/services/ABDMultiWebService"
  user: "etb2014$"
  pass: "etb2014$prod"
  boundary: "_Part_1484_1205094613.1721658606582"
  
mediafon:
  protocol: "HTTPS"
  host: "soap.portabilidad.co"
  port: "443"
  path: "/api/np/receiveMessage"
  user: "ETB_SOAP"
  pass: "Molayus*83"

# faltan propiedades productivas
sendMessage:
  protocol: "HTTP"
  host: "10.111.56.25"
  port: "8081"
  basePath: "/wservice"
  path: "/sendmessage.ws?wsdl"
  properties:
    sender: "7007"
    mode: "1"
    code: "ACCEPTED"
dgo:
  protocol: "HTTP"
  host: "dtv-prov.tbxapis.com"
  port: ""
  basepath: "/v1"
  country: "CO"
  password: "Directv123"
  key: "Q1kAKAPJezx6lhvJVT0omIAXhRfGgWwn"
  path:
    getSubscriber: "/subscriber/{country_code}/{subscriber_id}"
    postSubscriber: "/subscriber"
    addUrn: "/subscriber/{country_code}/{subscriber_id}/urn"
    deactivateUser: "/subscriber/{country_code}/{subscriber_id}/deactivate"
mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mongo/v1"
  path:
    agreements-logs: "/agreements/logs"
    parameters: "/parameters/{typeParameter}"
  typeParameter-azsing: "PARAMETROS_FIRMA_DIGITAL_AZSIGN"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
azsign:
  protocol: "HTTPS"
  host: "azsign.analitica.com.co"
  port: "443"
  basePath: "/WebServices"
  path: "/SOAP/"
  typeDocuments: "CC|CE"

atp:
  protocol: "HTTPS"
  host: "atp.tecnotree.com"
  port: "443"
  basepath: "/"
  path:
    auth: "/dap-is/dap-api-rest-user-jwtauth"
    speedChange: "/speedChange/tmf-api/serviceActivationAndConfiguration/v4/service"
    serviceQualification: "/serviceQualification/tmf-api/serviceQualificationManagement/v4/checkServiceQualification"
    serviceActivation: "/serviceActivation/tmf-api/serviceActivationAndConfiguration/v4/service"
    serviceTermination: "/serviceTermination/tmf-api/serviceActivationAndConfiguration/v4/service"
    serviceModification: "/serviceModification/tmf-api/serviceActivationAndConfiguration/v4/service"
  flow:
    bookingFeasibility: "post-atpServiceQualification-clientSub_Flow"
    createBooking: "post-atpServiceQualification-clientSub_Flow"
    consultBooking: "post-atpServiceQualification-clientSub_Flow"
    cancelBooking: "post-atpServiceQualification-clientSub_Flow"
    activateOnt: "post-atpServiceActivation-clientSub_Flow"
    activateService: "post-atpServiceActivation-clientSub_Flow"
    deactivateOnt: "post-atpServiceTermination-clientSub_Flow"
    deactivateService: "post-atpServiceTermination-clientSub_Flow"
    resetONT: "post-atpServiceActivation-clientSub_Flow"
    consultLevels: "post-atpServiceActivation-clientSub_Flow"
    consultSpeed: "post-atpServiceActivation-clientSub_Flow"
    consultState: "post-atpServiceActivation-clientSub_Flow"
    consultNeighbors: "post-atpServiceActivation-clientSub_Flow"
    serviceSuspension: "post-atpServiceModification-clientSub_Flow"
    serviceReactivation: "post-atpServiceModification-clientSub_Flow"
    speedChangeFeasibility: "post-atpServiceQualification-clientSub_Flow"
    speedChangeCreateBooking: "post-atpServiceQualification-clientSub_Flow"
    speedChangeCancelBooking: "post-atpServiceQualification-clientSub_Flow"
    speedChange: "post-atpServiceQualification-clientSub_Flow"
  username: "appEtb"
  password: "@appEtb"
  days: "1"
  muleValidation: "bookingFeasibility|createBooking|activateOnt|activateService|deactivateOnt|deactivateService|resetONT|consultLevels|consultSpeed|consultState|consultNeighbors|serviceSuspension|serviceReactivation|speedChange"
  #consultBooking|cancelBooking|speedChangeFeasibility|speedChangeCreateBooking|speedChangeCancelBooking
  
ldap:
  url: "ldap://10.113.57.20:389"
  principalDn: "cn=userdataintegrator,ou=Grupos,o=etb"
  password: "Mayo2013"
  authentication: "simple"
  baseDn: "o=etb"
  pool:
    initial: "1"
    max: "5"
    timeout: "60000"  