http:
  private:
    port: "8091"
  
autodiscovery: ""
 
mongo-db-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/mongo/v1"
  resources:  
    customer:
      base-path: "/customer"
      get:
        path: ""
      post:
        path: ""
      patch:
        path: ""

  security:
    client-id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client-secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

configurationTimeout:
  customer-papi-v2-listener: "62000"
  mongo-db-sapi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"