http:
  private:
    port: "8091"
  host: "0.0.0.0"
  
cancelOrder:
  shalogin: "d84e890edec6c5138c007e487f6bab8a3d92be53"
  shapass: "26bf8b8ecc750f9e8c2480e1582f31a5a1aae65b8d28b113934932df720b2a9d"
  company: "etb"
  processing_mode: "appointment_only"
  upload_type: "incremental"
  appointment_keys_field: "appt_number"
  inventory_keys_field1: "invsn"
  inventory_keys_field2: "invtype"
  inventory_upload_type: "incremental"
  command_type: "cancel_appointment"
  
createOrderAssurance:
  shalogin: "d84e890edec6c5138c007e487f6bab8a3d92be53"
  company: "etb"
  processing_mode: "appointment_only"
  upload_type: "incremental"
  appointment_keys_field: "appt_number"
  inventory_keys_field1: "invsn"
  inventory_upload_type: "incremental"
  properties_mode: "update"
  command_type: "update_appointment"

createOrder:
  shalogin: "d84e890edec6c5138c007e487f6bab8a3d92be53"
  shapass: "26bf8b8ecc750f9e8c2480e1582f31a5a1aae65b8d28b113934932df720b2a9d"
  company: "etb"
  processing_mode: "appointment_only"
  upload_type: "incremental"
  appointment_keys_field: "appt_number"
  inventory_keys_field1: "invsn"
  inventory_keys_field2: "invtype"
  inventory_upload_type: "incremental"
  command_type: "update_appointment"
  allow_change_date: "yes"
  properties_mode: "update"  
  command_type2: "update_appointment"

oracle-ocs:
  protocol: "HTTPS"
  host: "etb.fs.ocs.oraclecloud.com"
  port: "443"
  basePath: "/"
  shalogin: "d84e890edec6c5138c007e487f6bab8a3d92be53"
  shapass: "26bf8b8ecc750f9e8c2480e1582f31a5a1aae65b8d28b113934932df720b2a9d"
  company: "etb"
  content-type: "text/xml;charset=UTF-8"
  revInvList:
    path: "rest/ofscCore/v1/resources/{externalId}/inventories"
    username: "6ea4f1cafed30769a0c3a3be459dd495d53e1f0a@etb"
    pass: "37c2bf4c601582e1984a065b09298ae1b820f573e4ed0e642510b84a2e16de27"
    Boffset: "0"
  cancelOrder:
    path: "/soap/inbound/"
    action: "InboundInterfaceService/inbound_interface"
    content-type: "text/xml;charset=UTF-8"
  capacity:
    path: "/soap/capacity/"
    action: "toa_capacity_interface/get_capacity"
  syncOrder:
    path: "/rest/ofscCore/v1/activities/{activityId}"  
    user: "USER"
    company: "COMPANY"
    pass: "PASSWORD"
  createAssuranceOrder:
    path: "/rest/ofscCore/v1/activities"
    path_put: "/rest/ofscCore/v1/activities/{Activity_ID}/XA_adjunto"
    user: ""
    pass: ""
    XA_request_type: "inmediata"
oracle-db:
  host: "10.112.2.30"
  port: "1540"
  user: "tib_ipe_adm"
  password: "tib_ipe_adm_14"
  serviceName: "TBFOMQA"
  
oracle-db-normalize:
  host: "scan-racbssprd.etb.com.co"
  port: "1538"
  user: "SISEXTCONS"
  password: "CONSSIS2013"
  serviceName: "SISEXT"
  maximumPoolSize: "100"
  connectionTimeout: "10000"
  jdbcUrl: "jdbc:oracle:thin:@//${oracle-db-normalize.host}:${oracle-db-normalize.port}/${oracle-db-normalize.serviceName}"
  specialMunicipiosCode: "ciudex"
  
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

responsys:
  auth:
    host: "login5.responsys.net"
    port: "443"
    protocol: "HTTPS"
    basepath: "/rest/api/v1.3"
    path: "/auth/token"
    user: "integrations_ETB"
    password: "BogotaETB2019!"
    type: "password"
    content-type: "application/x-www-form-urlencoded"
  registerPetition:
    basepath: "/rest/api/v1.3"
    content-type: "application/json"
    rules:
      insert: "true"
      update: "REPLACE_ALL"
      matchEmail: "EMAIL_ADDRESS_"
      matchSMS: "MOBILE_NUMBER_"
    url_mietb: "https://mietb.etb.com/"
    
bot-sapi:
  host: "mule-worker-internal-bot-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/operations/v1"
  path: "/generateRegisterUrl/{email}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

oracle-db-logs:
  host: "hadesvm02-scan7.etb.com.co"
  port: "1521"
  sid: "MULEPRD"
  username: "MULEAPP"
  password: "Mul3*2023"
  catalogo: "CT20TIPDOCCIFIN"
  poolSize: "200"
  connectionTimeout: "5000"

mongo-sapi-services:
  protocol: "http"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/mongo/v1"
  parameters:
    path: "/parameters/{typeParameter}"
    param: "PARAMETROS_OFSC"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

remedy-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-remedy-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/remedy/v1"
  task:
    path: "/incident/{incidence_id}/tasks"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"    

autodiscovery: "17965571"

configurationTimeout:
  oracle-ocs: "60000"
  responsys: "60000"
  bot-sapi: "60000"
  listener: "30000"
  mongo-sapi: "60000"
  remedy-sapi: "60000"
  procesossuma: "60000"
    
procesossuma:
   host: "procesossuma.app.etb.co"
   port: "80"
   protocol: "HTTP"
   basepath: "/Api/Responsys"
   path: "/EnvioGeneral"