https:
  host: "0.0.0.0"
  port: "443" 
  
autodiscovery: "20514478"

bot-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/api"
  endpoints:
    whatsapp:
      base-path: "/whatsapp"
      getbyphone: "/getbyphone/v1"
      update: "/update/v1"
    customers:
      base-path: "/customers"
      settyc: "/settyc/v1"
    scraping:
      base-path: "/scraping"
      satisfactionsurvey: "/satisfactionsurvey/v1"
      
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
bot-sapi-2:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-2-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/bot/v1"
  endpoints:
    services:
      base-path: "/services"
      getcontract: "/getcontract"
      
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "9070fd1dac714b1b9e041c0d8fdff6ce"
  client_secret: "A2De130A74084573Bc8352790a8C1b56"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"

configurationTimeout:
  bot-sapi: "62000"
  bot-sapi-2: "62000"