https:
  host: "0.0.0.0"
  port: "443"
  
autodiscovery: "19315029"
api_id: "mvne-xapi-services-prod"

global-vars:
  refill: "Refill"
  pkgaddon: "Pkgaddon"
  activo: "ACTIVO"
  inactivo: "INACTIVO"
  validarMigracion: "true"
  migradoMvne: "MigradoMVNE"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

service-papi-services:
  protocol: "HTTP"
  host: "mule-worker-internal-service-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/services/v1"
  path:
    activate: "/ordenes/movilidad/{id}/activate"
    recharge: "/ordenes/movilidad/recargar"
    disponibilidad: "/ordenes/movilidad/disponibilidad"
    subscription: "/operations/subscription/{connectionNumber}"
    replacement: "/replacement"
    replacementPlan: "/replacement/plan"
    sva: "/sva"
    consultarSaldo: "/svas/{id}"
    getBagsOffer: "/bagsOffer"
    comprarBolsas: "/svas"
    getBalance: "/subscription/balance"
    getBalancev2: "/balance/{msisdn}"
    transferbalance: "/transferbalance"
    activate-esim: "/activate/eSim"
    sendMessage: "/send-message"
    logMessage: "/log-messages"
    suscriber: "/suscriber/{suscriberId}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion": "mvne-xapi-services"    

operations-papi-services:
  protocol: "HTTP"
  host: "mule-worker-internal-operations-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/operations/v1"
  path:
    subscriptionReplacement: "/subscription/replacement"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion": "mvne-xapi-services"    

audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs"
  path: "/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
azure-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-azure-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/azure/v1"
  path:
    keyVault: "/keyVault/{key}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

oAuthSapi:
  protocol: "HTTPS"
  host: "oauth-etb-security-services-prod.us-e2.cloudhub.io"
  port: "8082"
  basepath: "/security/v2"
  path: "/access_token"
  pathValidate: "/validate"

oAuth:
  key: "B0TApp062019"

token-v2:
  #Need to be the same from oauth-sapi
  secretBody: "MuleSoft2024"
  keyAES: "B0TApp062019"
  saltAES: "B0TApp062019"
  issuer: "Mulesoft"
  audience: "MiEtb"
  expiration: "1800000"
  secret: "MuL3Asoft2024"
  enviroment: "prod"
mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  basepath: "/mongo"
  path:
    systems: "/v1/ms/systems/{name}"
    productOffer: "/v1/productOfferByGroupingNumber"  
    active-service: "/v1/active-service"
sisext-sapi:
  port: "8091"
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  basepath: "/sisext/v1"
  path: "/RNE"
  path-captcha: "/captcha"
  path-recharge: "/air/recharge"
  protocol: "HTTP"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

configurationTimeout:
  services-papi: "62000"
  audits-mongo: "62000"
  azure-sapi: "62000"
  oAuth: "62000"
  mongo-sapi: "62000"
  sisext-sapi: "62000"  
  jsc-sapi: "61000"
    
jsc-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-jsc-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/jsc/v1"
  subscriber:
    path: "/subscriber"
    subscriberType: "EXTERNAL"
    errorMessage: "Error retrieving subscriber"
  subscription:
    path: "/subscription"
    getBySID: "/subscription/group/{SID}"
    errorMessage: "Error retrieving info subscription"
    get-svas:
      caracteristica: "JSC ID"
  assignSubscriptionToSubscriber:
    path: "/subscription/{subscription_id}/change-owner/{subscriber_id}"
  billingAccount:
    consult:
      path: "/billing/ba"
      name: "Creating a new BillingAccount"
      errorMessage: "Error creating billing account ba"
      errorMessage2: "Error retrieving info billing account ba"
    modify:
      path: "/billing/ba/{id}"
      name: "Creating a new BillingAccount"
      errorMessage: "Error creating billing account ba"
      errorMessage2: "Error retrieving info billing account ba"