http:
  private:
    port: "8091"
  
autodiscovery: "18532897"

botServices:
  protocol: "HTTP"
  host: "10.60.22.4"
  port: "91"
  basepath: "/api"
  responseTimeout: "60000"
  authenticate:
    path: "/security/v1/authenticate"
    user: "MULESOFT"
    pass: "mUL31nT3G22F"
  saleOrderGetCustomer:
    path: "/saleorder/v1/customer/get"
  saleOrderGetCatalog:
    path: "/saleorder/v1/commercialcatalog/get"
  saleOrderValidateCatalog:
    path: "/saleorder/v1/commercialcatalog/validate"
  saleOrderGetPending:
    path: "/saleorder/v1/pending"
  saleOrderOpInit:
    path: "/saleorder/v1/init"
  saleOrderOpCreate:
    path: "/saleorder/v1/create"
  saleOrderOpValidation:
    path: "/saleorder/v1/validation"
  saleOrderOpOtp:
    path: "/saleorder/v1/otp"
  saleOrderOpQuestionnaire:
    path: "/saleorder/v1/form"
  saleOrderOpCancel:
    path: "/saleorder/v1/cancel"
  saleOrderOpUpdate:
    path: "/saleorder/v1/update"
  saleOrderGet:
    path: "/saleorder/v1/get"
  saleOrderOpBooking:
    path: "/saleorder/v1/agendaavailable"
  saleOrderFilterCatalog:
    path: "/saleorder/v1/commercialcatalog/filter"
  saleOrderSimcards:
    path: "/saleorder/v1/sendsimcard"
  saleOrderPortabilitiesOperation:
    path: "/saleorder/v1/portability"
  saleOrderPayments:
    path: "/saleorder/v1/pay"
  parameterGetCities:
    path: "/parameters/v1/getcities"
  parameterGetDepartment:
    path: "/parameters/v1/getdepartment"
  parameterGetOperators:
    path: "/parameters/v1/getoperators"
  parameterGetBusinessdays:
    path: "/parameters/v1/getbusinessdays"
  parameterGetServicesTypePortability:
    path: "/parameters/v1/getservicestypeportability"
  pqrReagenda:
    path: "/pqr/v2/reagenda"
  pqrAgendaClose:
    path: "/pqr/v2/agendaclose"
  pqrCreate:
    path: "/pqr/v3/create"
  pqrGet:
    path: "/pqr/v3/get"
  pqrUpdate:
    path: "/pqr/v1/update"
  pqrAgenda:
    path: "pqr/v2/agenda"
  ordersGet:
    path: "/orders/v4/get"
  ordersRelocate:
    path: "/orders/v2/relocate"
  maxRoute:
    path: "/max/v2/route"
  whatsappGetByPhone:
    path: "/whatsapp/v1/getbyphone"
  whatsappUpdate:
    path: "/whatsapp/v1/update"
  customersSettyc:
    path: "/customers/v1/settyc"
  customersMecna:
    path: "/customers/v1/mecna"
  scrapingSatisfactionsurvey:
    path: "/scraping/v1/satisfactionsurvey"
  servicesGetinvoices:
    path: "/services/v4/getinvoices"
  servicesGetbalance:
    path: "/services/v2/getbalance"
  servicesReconexion:
    path: "/services/v2/reconexion"
  servicesGet:
    path: "/services/v4/get"
  servicesWithoutdebt:
    path: "/services/v1/withoutdebt"
  servicesWhypay:
    path: "/services/v2/whypay"
  servicesRequestinvoice:
    path: "/services/v4/requestinvoice"
  supportInit:
    path: "/support/v1/init"
  soporte1nNormalizeinternet:
    path: "/soporte1n/v3/normalizeinternet"
  soporte1nGetwifi:
    path: "/soporte1n/v3/getwifi"
  soporte1nValidatetv:
    path: "/soporte1n/v1/validatetv"
  soporte1nNormalizetv:
    path: "/soporte1n/v2/normalizetv"
  soporte1nSetwifinetworkpassword:
    path: "/soporte1n/v3/setwifinetworkpassword"
  soporte1nNormalizelb:
    path: "/soporte1n/v2/normalizelb"
  generateRegisterURL:
    path: "/mietb/v1/generateregisterurl"    
  mietbAuthmail:
    path: "/mietb/v1/authmail"
    
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    
commons:
  systemName: "Mulesoft"
  auditsChannel: "WEB"