http:
  host: "0.0.0.0"
  private:
    port: "8091"

autodiscovery: "17964318"

configurationTimeout:
  smallworld: "70000"
  
smallworld:
  host: "10.112.1.61"
  port: "8080"
  basepath: "/gss/web/services"
  path: "/WSGeorreferenciarCRService?wsdl"
  protocol: "HTTP"
  soapProtocol: "http"
  services:
    zonaAltoRiesgo:
      serviceName: "WsConsultarZonaAltoRiesgoService"
      portName: "WsConsultarZonaAltoRiesgoService-SOAP11port_http"
      
smallworld-2:
  host: "10.112.1.67"
  port: "8080"
  basepath: "/gss/web/services"
  soapProtocol: "http"
  services:
    zonaAltoRiesgo:
      serviceName: "WsConsultarZonaAltoRiesgoService"
      portName: "WsConsultarZonaAltoRiesgoService-SOAP11port_http"

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
credentials:
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
anypoint:
  platform:
    client_id:
      xxxxx  
    client_secret:
      xxxxx
env:
  prod
security:
  client_id:
    xxxx
  client_secret:
    xxx

# Enable retry in georeference process but changering the address: AC->CL, CL->AC, AK->KR, KR->AK
georetry: "yes"