#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: consulta realizadaexitosamente
    required: false
  utilitys:
    type: object
    required: false
    properties:
      parameters:
        type: array
        required: false
        items:
          type: object
          properties:
            _id:
              type: string
              example: 63aa250b68e75244f4e3621a
              required: false
            creationDate:
              type: datetime
              example: '2022-12-13T23:57:15.052Z'
              required: false
            modificationDate:
              type: datetime
              example: '2022-12-13T23:57:15.052Z'
              required: false
            modifiedByUser:
              type: string
              example: holmroda
              required: false
            createdByUser:
              type: string
              example: holmroda
              required: false
            extractorUpdate:
              type: string
              example: '1'
              required: false
            parameterType:
              type: integer
              example: 37
              required: false
            name:
              type: string
              example: Motivo_Submotivo
              required: false
            values:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                    required: false
                  status:
                    type: integer
                    example: 0
                    required: false
                  value:
                    type: string
                    example: '100'
                    required: false
                  attributeClass:
                    type: integer
                    example: 4
                    required: false
                  attributeType:
                    type: integer
                    example: 9
                    required: false
                  relations:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 1
                          required: false
                        status:
                          type: integer
                          example: 0
                          required: false
                        value:
                          type: string
                          example: '200'
                          required: false
                        attributeClass:
                          type: integer
                          example: 5
                          required: false
                        attributeType:
                          type: integer
                          example: 9
                          required: false
                        relations:
                          type: array
                          items: {}
                        rules:
                          type: array
                          items: {}
                        levels:
                          type: array
                          items:
                            type: integer
                        name:
                          type: string
                          example: MOTIVO_SUBMOTIVO
                          required: false
                  rules:
                    type: array
                    items: {}
                  levels:
                    type: array
                    items:
                      type: integer
            steps:
              type: array
              items: {}
            actions:
              type: array
              items: {}
            reasonSteps:
              type: array
              items: {}
            ruleSteps:
              type: array
              items: {}
      operators:
        type: array
        required: false
        items: {}
      bussinesdays:
        type: array
        required: false
        items: {}
