http:
  private:
    port: "8091"
  time-out: "30000"

configurationTimeout:
  mdm-db: "60000"
  or-db: "60000"
  prtl_pro_bd: "60000"
  audits-mongo: "60000"
  zonag-mongo: "90000"
  

api_id: "mongo-db-sapi-services-prod"
  
mongoDb-mdm:
  host_list:
    host1: "VM-AZMONGOS03.etb.cloud"
    host2: "VM-AZMONGOS04.etb.cloud"
  port: "27030"
  database: "MDM"
  database-parametrization: "PRTL_PRO_BD"
  username: "Mule_mongo_prod"
  password: "Z*s985S8"
  collection-wspPlantilla: "ADM_WHATSAPP_PLANTILLAS"
  collection-esim: "MDM_ACTIVACION_ESIM"
  collection-esim-log: "MDM_ACTIVACION_ESIM_LOG"
  portabilidadProcesos: "MDM_PORTABILIDAD_SOLICITUDES"
  collection-order: "MDM_ORDEN"
  #portabilidadProcesos: "MDM_PORTABILIDAD_PROCESOS"
  collection-operators: "PAR_OPERADORES_PORTABILIDAD"
  collection-bussiness-days: "PAR_DIA_FESTIVO"
  collection-productOffering: "CMP_OFERTA_PRODUCTO"
  collection-beneficiosPromocion: "PROM_BENEFICIOS_PROMOCION"
  collection-promocion: "PROM_PROMOCION"
  collection-portal-unificado: "PORTAL_UNIFICADO_CONFIGURACION"
  
 
  mayoristas:
    collection-order: "MDM_CD_ORDEN"
    collection-order-completed: "MDM_CD_ORDEN_COMPLETADA"
    
  mulesoft:
    tokens: "MULESOFT_TOKENS"
    clients: "MULESOFT_CLIENTES"
    systems: "MULESOFT_SISTEMAS"
    
  agendas:
    collection-pqr-agenda-tmr: "PQR_AGENDA_TMR"
  
  serviceProblem: 
    collection-pqr: "PQR_PQR"
    collection-consecutives: "PAR_CONSECUTIVOS"
    
  audits:
    collection-dijin: "MDM_AUDITORIA_DIJIN"
  clientes:
    collection-cliente: "MDM_CLIENTE"
  parametros:
    collection-parametro: "MDM_CD_PARAMETRO"
    collection-parametros-retencion: "CD_PARAMETROS_RETENCION"
  servicios:
    collection-service-active: "MDM_SERVICIO_ACTIVO"
    collection-service-ftth: "MDM_CD_SERVICIO"
  facturas:
    collection-facturacion: "MDM_CUENTA_FACTURACION"
  retenciones:
    collection-retencion: "CD_RETENCION"
    collection-retencion-consecutivo: "MDM_CD_CONSECUTIVO"

mongoDb-zonag:
  host-list:
    host1: "VM-AZMONGOS03.etb.cloud"
    host2: "VM-AZMONGOS04.etb.cloud"
  port: "27030"
  database: "ZONAG"
  username: "USRPRTLDIR"
  password: "USRDIR3tb2020"
  geo-address-collection: "PD_GEO_DIRECCIONES"
        
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs/"
  path: "/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    
retryConfiguration:
  maxRetry: "3"
   
scheduler:
  frequency: "24"

cacheKeys:
  typeParameters: "TP"
  cardinalExpansion: "ADDRESS_CARDINAL_EXPANSION"

cardinalExpansion:
  cache:
    enabled: "true"
    ttl: "24"  # TTL en horas (configurado en global.xml)
  
logging:
  deniedProcessName: "send_message"
  mayoristas:
    causal: "OFF"
    clientes: "OFF"
    ordenes:
      obtener: "OFF"
      actualizar: "OFF"
      insertar: "OFF"
    ordenesModelo: "OFF"
    status: "OFF"
    servicios: "OFF"
    
autodiscovery: "20236559"


#Parametro de busqueda interaccion HSM en minutos
search-interaction: "15"