http:
  private:
    port: "8091"

configurationTimeout:
  mdm-db: "60000"
  or-db: "60000"
  prtl_pro_bd: "60000"
  audits-mongo: "60000"
  

api_id: "mongo-db-sapi-services-prod"
  
mongoDb-mdm:
  host_list:
    host1: "VM-AZMONGOS03.etb.cloud"
    host2: "VM-AZMONGOS04.etb.cloud"
  port: "27030"
  database: "MDM"
  database-parametrization: "PRTL_PRO_BD"
  username: "Mule_mongo_prod"
  password: "Z*s985S8"
  collection-wspPlantilla: "ADM_WHATSAPP_PLANTILLAS"
  portabilidadProcesos: "MDM_PORTABILIDAD_SOLICITUDES"
  #portabilidadProcesos: "MDM_PORTABILIDAD_PROCESOS"
  
 
  mayoristas:
    collection-order: "MDM_CD_ORDEN"
    collection-order-completed: "MDM_CD_ORDEN_COMPLETADA"
    
  mulesoft:
    tokens: "MULESOFT_TOKENS"
    clients: "MULESOFT_CLIENTES"
    systems: "MULESOFT_SISTEMAS"
  
  serviceProblem: 
    collection-pqr: "PQR_PQR"
    collection-consecutives: "PAR_CONSECUTIVOS"
    
  audits:
    collection-dijin: "MDM_AUDITORIA_DIJIN"
  clientes:
    collection-cliente: "MDM_CLIENTE"
  parametros:
    collection-parametro: "MDM_CD_PARAMETRO"
  servicios:
    collection-service-active: "MDM_SERVICIO_ACTIVO"
        
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs/"
  path: "/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    
retryConfiguration:
  maxRetry: "3"
   
scheduler:
  frequency: "24"

cacheKeys:
  typeParameters: "TP"
  
logging:
  deniedProcessName: "send_message"
  mayoristas:
    causal: "OFF"
    clientes: "OFF"
    ordenes:
      obtener: "OFF"
      actualizar: "OFF"
      insertar: "OFF"
    ordenesModelo: "OFF"
    status: "OFF"
    servicios: "OFF"
    
autodiscovery: "20236559"


#Parametro de busqueda interaccion HSM en minutos
search-interaction: "15"