http:
  private:
    port: "8091"
  
autodiscovery: "20435446"

anypoint:
  platform:
    client_id: "d0f8c76053564a4dbba306392a96fec0"
    client_secret: "58cB540Ae2504D668FbC77fB98286125"
    
mongoDb-sapi:  
  protocol: "HTTP"  
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/mongo/v1"
  path:
    productOffering: "/productOffering/query"    
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

bot-sapi-2:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-2-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/bot/v1"
  endpoints:
    services:
      base-path: "/services"
      validateimei: "/validateimei"
      suspendvoluntarily: "/suspendvoluntarily"
      suspendbytheft: "/suspendbytheft"
      
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
smallworld-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-smallworld-sapi-services-prod.us-e2.cloudhub.io"
  #host: "localhost"
  port: "8091"
  basepath: "/smallworld/v1"
  path: "/georeference"

sisext:
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  #host: "localhost"
  port: "8091"
  basepath: "/sisext/v1"
  feasibility:
    path: "/feasibility"
  coverage:
    path: "/coverageGIS"
  protocol: "HTTP"
  
configurationTimeout:
  sisext-sapi: "72000"
  smallworld-sapi: "72000"
  audits-mongo: "62000"
  mongoDb-sapi: "62000"
  listener: "61000"
  mongo-sapi: "61000"
  oracle-sapi: "61000"
  product-sapi: "62000"
  bot-sapi-2: "62000"
  
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
credentials: 
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

normalize-papi:
  protocol: "HTTP"
  basepath: "/normalize/v1"
  path: "/normalizeAddress"
  host: "mule-worker-internal-normalize-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  
orquestador-sapi:
  protocol: "HTTP"
  basepath: "/v1"
  path: "/neighborsAddress"
  host: "mule-worker-internal-orquestador-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
