http:
  private:
    port: "8091"
  
autodiscovery: ""

bot-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/api"
  endpoints:
    soporte1n:
      base-path: "/soporte1n"
      normalizeinternet: "/normalizeinternet/v1"
      normalizetv: "/normalizetv/v1"
      normalizelb: "/normalizelb/v1"
      setwifinetworkpassword: "/setwifinetworkpassword/v1"
      
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
bot-sapi-2:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-2-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/bot/v1"
  endpoints:
    soporte1n:
      base-path: "/soporte1n"
      setwifinetworkstate: "/setwifinetworkstate"
      
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"

configurationTimeout:
  bot-sapi: "62000"
  bot-sapi-2: "62000"