http:
  private:
    port: "8091"
  
autodiscovery: "20572001"

botServices:
  protocol: "HTTP"
  host: "10.60.22.4"
  port: "91"
  basepath: "/api"
  responseTimeout: "60000"
  authenticate:
    path: "/security/v1/authenticate"
    user: "MULESOFT"
    pass: "mUL31nT3G22F"
  resources:
    services:
      rootPath: "/services"
      suspendByTheft:
        path: "/v1/suspendbytheft"
      suspendVoluntarilyV2:
        path: "/v2/suspendvoluntarily"
      validateImeiV2:
        path: "/v2/validateimei"
      registerdevice:
        path: "/v2/registerdevice"
      suspendbyloss:
        path: "/v1/suspendbyloss"
      setdeliverytypeinvoiceV2:
        path: "/v2/setdeliverytypeinvoice"
      getcontract:
        path: "/v1/getcontract"
      sva:
        path: "/v1/sva"

    soporte1n:
      rootPath: "/soporte1n"
      setWifiNetworkStateV3:
        path: "/v3/setwifinetworkstate"
      validatelb:
        path: "/v1/validatelb"
      setwifinetworknameV3:
        path: "/v3/setwifinetworkname"
      validateaccess:
        path: "/v1/validateaccess"
      normalizeaccess:
        path: "/v1/normalizeaccess"

    customers:
      rootPath: "/customers"
      habeasdata:
        path: "/v2/habeasdata"
      createcontactphone:
        path: "/v1/createcontactphone"
        
    notifications:
      rootPath: "/notifications"
      sendinfosva:
        path: "/v1/sendinfosva"
      sendnotifyprocedure:
        path: "/v1/sendnotifyprocedure"
        
    mietb:
      rootPath: "/mietb"
      updatepassword:
        path: "/v1/updatepassword"

    orders:
      rootPath: "/orders"
      createchangenumberV2:
        path: "/v2/createchangenumber"
        
    saleorder:
      rootPath: "/saleorder"
      store:
        rootPath: "/v1/store"
        nipportability:
          path: "/nipportability"
          
    scheduledPayments:
      rootPath: "/ScheduledPayments"
      getSchedPay:
        path: "/v1/get"
      inactive:
        path: "/v1/inactive"
      insert:
        path: "/v1/insert"
    
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    
commons:
  systemName: "Mulesoft"
  auditsChannel: "WEB"
  
configurationTimeout:
  bot-sapi-2-listener: "62000"
  botServices:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"