https:
  host: "0.0.0.0"
  port: "443" 
  
autodiscovery: "20429970"

customer-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-customer-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/v1"
  resources:  
    customer:
      base-path: "/customer"
      get:
        path: ""
      post:
        path: ""
      patch:
        path: ""
      authorizationTdp:
        path: "/authorizationTdp"
    productOrder:
      base-path: "/productOrder"
      get:
        path: ""
      post:
        path: ""
      nip: "/nip"
    customerBill:
      base-path: "/customerBill"
      get:
        path: ""
      balance:
        path: "/balance"
      clearance:
        path: "/clearance"
      debts:
        path: "/debts"
      billPresentationMedia:
        path: "/billPresentationMedia"
    riskManagement:
      base-path: "/riskManagement"
      get:
        path: ""
    paymentMethod:
      base-path: "/paymentMethod"
      get:
        path: ""
      post:
        path: ""
      inactive:
        path: "/inactive"
        
  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"
  
configurationTimeout:
  customer-xapi-listener: "62000"
  customer-papi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"