audits-sapi:
  protocol: "HTTP"
  host: "audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "80"
  basePath: "/audits/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"