http:
  private:
    port: "8091"
    
variable:
  add: "ADD"
  delete: "DELETE"
  active: "Active"
  terminate: "TERMINATE" 
  modifyPasagigas: "MODIFY_PASAGIGAS"
  promocionFlag: "TRUE"

bot-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/api"
  endpoints:
    services:
     base-path: "/services"
     reconexion: "/reconexion/v1"
     getService: "/get/v1"
    ordenes:
     base-path: "/orders"
     relocate: "/relocate/v1"
    soporte1n:
     base-path: "/soporte1n"
     getwifi: "/getwifi/v1"
     validatetv: "/validatetv/v1"
     
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
bot-sapi-2:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-2-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/bot/v1"
  endpoints:
    services:
      base-path: "/services"
      validateimei: "/validateimei"
      suspendvoluntarily: "/suspendvoluntarily"
      suspendbytheft: "/suspendbytheft"
      suspendbyloss: "/suspendbyloss"
    soporte1n:
      base-path: "/soporte1n"
      validatelb: "/validatelb"
      validateaccess: "/validateaccess"
      
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

global:
  renoRepo:
    packageId: "ETB_ChangeSim"
  condicionPortado: "VENTA LTE NCP"
  condicionNuevo: "VENTA LTE"
  msgPerCall: "5"
  desencoladorFrec: "5"
  trxResetQueue: "1"
  deleteEncolador: "1"
  txrMaxPorHora: "100"
  timeToDeliveyPerCategories:
    otp: "80000"
    regulatory: "86400"
    campaign: "3600"

orderSubType: "Venta LTE NCP;Cambio Numero LTE NCP;PORTABILIDAD;CAMBIO NUMERO PORTADO"

configurationTimeout:
  jsc-sapi: "61000"
  mongo-sapi: "90000"
  sisext-sapi: "61000"
  mongo-cf-sapi: "90000"
  bot-sapi: "62000"
  bot-sapi-2: "62000"
  mongo-db-sapi: "61000"
  orquestador-sapi: "61000"

autodiscovery: "19324288"

subscriberCancel:
  status: "TERMINATED"
  action: "CHANGE_STATUS" 
  actionTerminate: "TERMINATE" 
  
jsc-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-jsc-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/jsc/v1"
  recharge:
    path: "/topup"
    currency: "COP"
    errorMessage: "Error while recharging the phone"
  subscriber:
    path: "/subscriber"
    subscriberType: "EXTERNAL"
    errorMessage: "Error retrieving subscriber"
    patch-resource: "/suscriber/{id}"
  subscription:
    path: "/subscription"
    getBySID: "/subscription/group/{SID}"
    msisdn: "/{msisdn}/imei"
    errorMessage: "Error retrieving info subscription"
    get-svas:
      caracteristica: "JSC ID"
  consumption:
    path: "/consumption/{id}/details"
    errorMessage: "Error while obtaining consumption details"
  order:
    path: "/order"
    type: "RETAIL"
    salesChannel: "OWN_CALLCENTER"
    status: "CONFIRMED" #[CANCELLED, PROCESSING, VERIFIED, VERIFYING, OPEN, CLOSED, FAILED, CONFIRMED, PENDING_VERIFICATION]
    errorMessage: "Error creating order"
    endOrder:
      path: "/order/{id}"
      action: "APPLY"
      errorMessage: "Error closing order"
  msisdn:
    path:
      patch-msisdn-status: "/msisdn/{msisdn}"
      post-activateLine: "/msisdn/{msisdn}/{order_id}"
      get-disponibilidad: "/msisdn/{msisdn}"
      post-msisdn: "/msisdn"
    actionUpdateStatus: "MODIFY"
    product: "FWA"
    errorMessage: "Error associating msisdn"
    pool:
      id: "654654"
      name: "PoolMsisdn_ETBMVNE"
    sourcePool:
      id: "65321"
      name: "ETB_ChangeMsisdn"
  simcard:
    path: 
      post-activateLine: "/sim/{iccid}/{order_id}"
      get-disponibilidad: "/sim/{iccid}"
    errorMessage: "Error associating simcard"
  createBillingAccount:
    ba:
      path: "/billing/ba"
      name: "Creating a new BillingAccount"
      errorMessage: "Error creating billing account ba"
      errorMessage2: "Error retrieving info billing account ba"
    subscription:
      path: "/subscription/{subscription_id}"
      action: "MODIFY"
      name: "Name"
      errorMessage: "Error creating billing account subscription"
      errorMessage2: "Error updating status"
      errorMessage3: "Error terminating the subscription"
      nameMoveSubsc: "Moving subscription to billing account cycle"
      nameAddMember: "Add member to group"
  pkgi:
    path: "/pkgi/{pkgi_id}"
    getbySID: "/pkgi"
    patch-pkgi: "/pkgi/{pkgi_id}"
    errorMessage-get: "Error al Obtener PKGI"
    errorMessage-patch: "Error al eliminar el PKGI"
  groupInstance:
    path: "/groupinstance/{groupInstanceId}/member"
    getById: "/groupinstance/member"
    deleteById: "/groupinstance/{groupInstanceId}/member/{memberId}"
    errorMessage-get: "Error al consultar member del group"
    errorMessage-delete: "Error al eliminar la linea hija del grupo"
    errorMessage-post: "No se pudo agregar línea hija al grupo"
  assignSubscriptionToSubscriber:
    path: "/subscription/{subscription_id}/change-owner/{subscriber_id}"
  subscription-id-feature:
    path: /subscription/{subscription_id}/features
    errorMessage-get: "Error while trying to obtain data from the subscription-feature"
    errorMessage-patch: "Error while trying to update data from the subscription-feature"
  balance-structured:
    path: "/balance"
    errorMessage: "Error while obtaining balance consumption details"
    size: "100"
    status: "ACTIVE"
  transferbalance:
    path: "/transferbalance"
    errorMessage: "Error while transfer balance"
    channel: "BALANCE_TRANSFER"
    comment: "Transferencia de saldo"
    currency: "COP"
  smpp:
    path: "/smpp/sendMessage"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

mongo-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/mongo/v1"
  sendMessage:
    path: "/send-message"
  enrutadorDatos:
    path: "/enrutadorMensajes"
    path_patch: "/enrutadorMensajes/{id}"
  logMessages:
    path: "/logMessages"
    sentInfo: "/logMessages/infoMessage"
  getToken:
    path: "/token"
    errorMessage: "Error retrieving token"
  path:
    services: "/referred/services"
    typeParameter: "/parameters/{typeParameter}"
    commercialCatalog: "/commercialCatalog"
    productOffer: "/productOfferByGroupingNumber"
  offers:
    path: "/offers/{id}"
  getCatalog:
    path: "/svas/{id}"
  usuarios:
    path: "/usuarios"
  getPromociones:
    path: "/promo"
  getPromXPkg:
    path: "/promo/pkg"
  getActiveService:
    path: "/services/active/{integrationId}"
  getOrderByCtaFact:
    path: "/order/{cuentaFacturacion}"  
  postPkgByPromotion:
    path: "/promoUser"

  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  getClient:
    path: "/clients"
  getReferral:
    path: "/referred"
    
referred:
  typeParameter: "EMPLEADOS_REFERIDOS"
  
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
sisext-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/sisext/v1"
  path: "/referred/{integrationId}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

global-vars:
  tecnologiaHogar: "FTTC,FTTH,COBRE"
  parametro-contactoFrecuente: "CANTIDAD_DIAS_CONSULTA_CONTACTO_FRECUENTE"
  
mongo-cf-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-mongo-cf-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/mongo/v1"
  path:
    exclusionClientes: "/clients/excluded"
    parametros: "/parameters/{typeParameter}"
    consultarOrdenes: "/orders"
    consultarEncuestas: "/encuestas/{numeroIdentificacion}"
    pqrs: "/pqrs"
    agendaTmr: "/pqrs/agenda_tmr"
    consultarTipoAtencion: "/tipoAtencion"
    contacto-frecuente: "/contactos-frecuentes"
    services: "/services"
    tramites: "/tramites"
    clientes: "/clients"
    interaction: "/interaction"
    msParameter: "/parametrization"
  consultarOrdenes:
    filtroTramite: "VTA"
  parametros:
    clienteRecurrente: "CLIENTE_RECURRENTE"
    agendaTmr:
      primero: "SemClienteRecurrente_Agendamiento"
      segundo: "RECURRENTE_CONSULTA_AGENDA_TMR_DIGITAL"
    visitasTecnicas: "RECURRENTE_CONSULTA_AGENDA_VISITA_DIGITAL"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

mongo-db-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/mongo/v1"
  path:
    get-esim: "/esim/{iccid}"
    get-orders: "/orders/{orderNumber}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
orquestador-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-orquestador-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/orquestador/v1"
  path:
    post-orderActivate: "/order/activate"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
parameters-esim:
  portabilidad: "PORTABILIDAD"
  fase-portacion: "PORTACION"
  id-vta: "PortalLTE_Activacion_Linea"
  id-reno: "PortalLTE_Activacion_RenoSIM"