#%RAML 1.0
title: bot-sapi-services-2
version: v1
baseUri: http://bot-sapi-services-{env}.us-e2.cloudhub.io/bot/{version}
protocols: [HTTP]
mediaType: application/json
description: |
  API para la comunicación con servicios del bot.

traits:
  security_client_id: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.3/security-clientid.raml
  request_headers: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml
  encrypted_headers: !include datatypes/request/objects/encrypt.raml

/services:
  /validateimei:
    post:
      is: [security_client_id, request_headers]
      displayName: Validate IMEI
      description: Validate IMEI
      body:
        application/json:
          type: !include /datatypes/request/post-valida-imei.raml
          example: !include /examples/request/post-valida-imei.json
      responses:
        200:
          description: IMEI validated successfully.
          body:
            application/json:
              type: !include /datatypes/response/post-valida-imei.raml
              example: !include /examples/response/post-valida-imei.json

  /suspendvoluntarily:
    post:
      is: [security_client_id, request_headers]
      displayName: Voluntary line suspension
      description: Voluntary line suspension
      body:
        application/json:
          type: !include /datatypes/request/post-suspend-voluntarily.raml
          example: !include /examples/request/post-suspend-voluntarily.json
      responses:
        200:
          description: Voluntary suspension completed successfully.
          body:
            application/json:
              type: !include /datatypes/response/post-suspend-voluntarily.raml
              example: !include /examples/response/post-suspend-voluntarily.json
  /registerdevice:
    post:
      is: [security_client_id, request_headers]
      displayName: Register device and link mobile line
      description: Register device and link mobile line
      body:
        application/json:
          type: !include /datatypes/request/post-register-device.raml
          example: !include /examples/request/post-register-device.json
      responses:
        200:
          description: The device was successfully registered and linked to the ETB mobile line.
          body:
            application/json:
              type: !include /datatypes/response/post-register-device.raml
              example: !include /examples/response/post-register-device.json

  /suspendbytheft:
    post:
      is: [security_client_id, request_headers]
      displayName: Suspend line due to theft
      description: Suspend line due to theft
      body:
        application/json:
          type: !include /datatypes/request/post-suspend-bytheft.raml
          example: !include /examples/request/post-suspend-bytheft.json
      responses:
        200:
          description: Suspension due to theft completed successfully.
          body:
            application/json:
              type: !include /datatypes/response/post-suspend-bytheft.raml
              example: !include /examples/response/post-suspend-bytheft.json

/soporte1n:
  /setwifinetworkstate:
    post:
      is: [security_client_id, request_headers]
      displayName: Change WiFi network status
      description: Change WiFi network status
      body:
        application/json:
          type: !include /datatypes/request/post-setwifi-networkstate.raml
          example: !include /examples/request/post-setwifi-networkstate.json
      responses:
        200:
          description: WiFi network status changed successfully.
          body:
            application/json:
              type: !include /datatypes/response/post-setwifi-networkstate.raml
              example: !include /examples/response/post-setwifi-networkstate.json

/customers:
  /habeasdata:
    post:
      is: [security_client_id, request_headers]
      displayName: Update habeasdata
      description: Update habeasdata
      body:
        application/json:
          type: !include /datatypes/request/post-update-habeasdata.raml
          example: !include /examples/request/post-update-habeasdata.json
      responses:
        200:
          description: Update of personal data processing decision successful.
          body:
            application/json:
              type: !include /datatypes/response/common-response-header.raml
              example: !include /examples/response/post-update-habeasdata.json

/notifications:
  /sendinfosva:
    post:
      is: [security_client_id, request_headers]
      displayName: Send SVA usage instructions
      description: Send SVA usage instructions
      body:
        application/json:
          type: !include /datatypes/request/post-send-infosva.raml
          example: !include /examples/request/post-send-infosva.json
      responses:
        200:
          description: The SVA usage instructions were successfully sent to the customer’s email address or as an SMS to the specified mobile number.
          body:
            application/json:
              type: !include /datatypes/response/common-response-header.raml
              example: !include /examples/response/post-send-infosva.json
  /sendnotifyprocedure:
    post:
      is: [security_client_id, request_headers]
      displayName: Send SIM replacement notification
      description: Send SIM replacement notification
      body:
        application/json:
          type: !include /datatypes/request/post-send-notifyprocedure.raml
          example: !include /examples/request/post-send-notifyprocedure.json
      responses:
        200:
          description: The SIM replacement notification was successfully sent to the customer’s email address.
          body:
            application/json:
              type: !include /datatypes/response/common-response-header.raml
              example: !include /examples/response/post-send-notifyprocedure.json
